"""Rename name to user_name in feedback table

Revision ID: 0e145232ad2a
Revises: 79a74ad45c3c
Create Date: 2024-07-22 19:09:45.519408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e145232ad2a'
down_revision: Union[str, None] = '79a74ad45c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('user_name', sa.String(), nullable=False))
    op.drop_column('feedback', 'name')
    op.alter_column('feedback', 'user_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_column('feedback', 'user_name')
    # ### end Alembic commands ###
