"""Add UserFavoriteStocks table

Revision ID: 6d3339394c72
Revises: 3a75c123f477
Create Date: 2024-07-28 15:24:05.713489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3339394c72'
down_revision: Union[str, None] = '3a75c123f477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_stocks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('stock_ticker', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['stock_ticker'], ['active_stocks.ticker']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_favorite_stocks_id'), 'user_favorite_stocks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_favorite_stocks_id'), table_name='user_favorite_stocks')
    op.drop_table('user_favorite_stocks')
    # ### end Alembic commands ###

